-- name: CreateOrder :execlastid
INSERT INTO
    `order` (
        shop_id,
        platform_id,
        remote_order_id,
        display_order_id,
        delivery_date_time,
        total_amount,
        sub_total,
        total_fee,
        campaign_code,
        discount,
        discount_type,
        vouchers,
        status,
        cancelled_reason,
        order_type_id,
        note,
        created_at,
        updated_at,
        customer_name,
        user_id,
        customer_id,
        delivery_location_id,
        shipping_method,
        shipping_total,
        shipping_tax,
        total_tax,
        cash_due,
        surcharge,
        contact_access_code,
        testing_order,
        cancelled_by_customer,
        payment_method,
        is_scheduled,
        is_table_order,
        tip,
        tip_percentage,
        table_id,
        table_order_method_id,
        device_platform,
        order_delayed,
        unique_order_id
    )
VALUES (
        ?,
        sqlc.arg (delivery_platform_id),
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    );

-- name: UpdateOrderStatus :exec
UPDATE `order` SET status = ? WHERE id = ?;

-- name: GetOrders :many
SELECT * FROM `order` WHERE order_type_id = 4 LIMIT ? OFFSET ?;