// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type DeliveryPlatform struct {
	ID                 uint64         `json:"id"`
	PlatformID         sql.NullInt32  `json:"platformId"`
	Name               string         `json:"name"`
	WebshopBrandID     sql.NullInt32  `json:"webshopBrandId"`
	ApiUrl             sql.NullString `json:"apiUrl"`
	AuthUrl            sql.NullString `json:"authUrl"`
	ApiParameters      sql.NullString `json:"apiParameters"`
	Logo               sql.NullString `json:"logo"`
	Status             string         `json:"status"`
	CreatedAt          sql.NullTime   `json:"createdAt"`
	UpdatedAt          sql.NullTime   `json:"updatedAt"`
	OutletCode         sql.NullString `json:"outletCode"`
	SiteID             sql.NullString `json:"siteId"`
	BranchID           sql.NullString `json:"branchId"`
	AccessToken        sql.NullString `json:"accessToken"`
	PrimaryColor       sql.NullString `json:"primaryColor"`
	CanUpload          bool           `json:"canUpload"`
	AutoAccepting      bool           `json:"autoAccepting"`
	FranchiseID        int32          `json:"franchiseId"`
	OutletID           sql.NullInt64  `json:"outletId"`
	MenuID             sql.NullString `json:"menuId"`
	MenuUploadStatus   sql.NullString `json:"menuUploadStatus"`
	StoreStatus        sql.NullString `json:"storeStatus"`
	AvailableFrom      sql.NullTime   `json:"availableFrom"`
	TenderTypes        sql.NullString `json:"tenderTypes"`
	IsMaster           bool           `json:"isMaster"`
	ParentPlatform     sql.NullInt32  `json:"parentPlatform"`
	PrepTime           sql.NullInt32  `json:"prepTime"`
	OwnDriver          bool           `json:"ownDriver"`
	MenuPublishedAt    sql.NullTime   `json:"menuPublishedAt"`
	WebshopSetupStatus bool           `json:"webshopSetupStatus"`
	HasCashPayment     bool           `json:"hasCashPayment"`
	HasCardPayment     bool           `json:"hasCardPayment"`
	SelectedMenu       sql.NullInt32  `json:"selectedMenu"`
	DeletedAt          sql.NullTime   `json:"deletedAt"`
}

type DgPosPayment struct {
	ID              uint64         `json:"id"`
	OrderID         int32          `json:"orderId"`
	DateTime        sql.NullTime   `json:"dateTime"`
	Amount          string         `json:"amount"`
	Cash            string         `json:"cash"`
	Balance         string         `json:"balance"`
	TransactionID   sql.NullString `json:"transactionId"`
	RefundID        sql.NullString `json:"refundId"`
	PaymentMethodID string         `json:"paymentMethodId"`
	Status          sql.NullString `json:"status"`
	IsRefund        bool           `json:"isRefund"`
	CreatedAt       sql.NullTime   `json:"createdAt"`
	UpdatedAt       sql.NullTime   `json:"updatedAt"`
}

type EntityDeliveryPlatform struct {
	ID                 uint64         `json:"id"`
	EntityID           sql.NullInt32  `json:"entityId"`
	DeliveryPlatformID int32          `json:"deliveryPlatformId"`
	ExternalItemID     string         `json:"externalItemId"`
	CreatedAt          sql.NullTime   `json:"createdAt"`
	UpdatedAt          sql.NullTime   `json:"updatedAt"`
	Plu                sql.NullString `json:"plu"`
	Price              sql.NullString `json:"price"`
	ItemName           sql.NullString `json:"itemName"`
	Allergies          sql.NullString `json:"allergies"`
	Available          bool           `json:"available"`
	AvailableFrom      sql.NullTime   `json:"availableFrom"`
}

type MainMenuMenu struct {
	ID         uint64       `json:"id"`
	MainMenuID int32        `json:"mainMenuId"`
	MenuID     int32        `json:"menuId"`
	CreatedAt  sql.NullTime `json:"createdAt"`
	UpdatedAt  sql.NullTime `json:"updatedAt"`
}

type Order struct {
	ID                  uint64         `json:"id"`
	ShopID              int32          `json:"shopId"`
	PlatformID          int32          `json:"platformId"`
	RemoteOrderID       string         `json:"remoteOrderId"`
	DisplayOrderID      string         `json:"displayOrderId"`
	DeliveryDateTime    time.Time      `json:"deliveryDateTime"`
	TotalAmount         int32          `json:"totalAmount"`
	SubTotal            int32          `json:"subTotal"`
	TotalFee            sql.NullInt32  `json:"totalFee"`
	CampaignCode        sql.NullString `json:"campaignCode"`
	Discount            int32          `json:"discount"`
	DiscountType        sql.NullString `json:"discountType"`
	Vouchers            sql.NullString `json:"vouchers"`
	Status              string         `json:"status"`
	CancelledReason     sql.NullString `json:"cancelledReason"`
	OrderTypeID         int32          `json:"orderTypeId"`
	Note                sql.NullString `json:"note"`
	CreatedAt           sql.NullTime   `json:"createdAt"`
	UpdatedAt           sql.NullTime   `json:"updatedAt"`
	CustomerID          int32          `json:"customerId"`
	CustomerName        string         `json:"customerName"`
	UserID              int32          `json:"userId"`
	DeliveryLocationID  sql.NullInt32  `json:"deliveryLocationId"`
	ShippingMethod      string         `json:"shippingMethod"`
	ShippingTotal       sql.NullString `json:"shippingTotal"`
	ShippingTax         sql.NullString `json:"shippingTax"`
	TotalTax            sql.NullString `json:"totalTax"`
	CashDue             string         `json:"cashDue"`
	Surcharge           string         `json:"surcharge"`
	ContactAccessCode   sql.NullString `json:"contactAccessCode"`
	TestingOrder        bool           `json:"testingOrder"`
	CancelledByCustomer bool           `json:"cancelledByCustomer"`
	PaymentMethod       string         `json:"paymentMethod"`
	IsScheduled         bool           `json:"isScheduled"`
	IsTableOrder        bool           `json:"isTableOrder"`
	Tip                 string         `json:"tip"`
	TipPercentage       string         `json:"tipPercentage"`
	TableID             sql.NullString `json:"tableId"`
	TableOrderMethodID  sql.NullInt32  `json:"tableOrderMethodId"`
	DevicePlatform      string         `json:"devicePlatform"`
	OrderDelayed        bool           `json:"orderDelayed"`
	UniqueOrderID       sql.NullString `json:"uniqueOrderId"`
}

type OrderItem struct {
	ID             uint64         `json:"id"`
	OrderID        int32          `json:"orderId"`
	ItemID         string         `json:"itemId"`
	Quantity       float64        `json:"quantity"`
	PricePerItem   int32          `json:"pricePerItem"`
	Total          int32          `json:"total"`
	OriginalPrice  int32          `json:"originalPrice"`
	IsSale         bool           `json:"isSale"`
	DiscountAmount int32          `json:"discountAmount"`
	Status         string         `json:"status"`
	CreatedAt      sql.NullTime   `json:"createdAt"`
	UpdatedAt      sql.NullTime   `json:"updatedAt"`
	ItemName       string         `json:"itemName"`
	CategoryName   sql.NullString `json:"categoryName"`
	Modifiers      sql.NullString `json:"modifiers"`
	Tax            int32          `json:"tax"`
	Note           sql.NullString `json:"note"`
}

type OrderItemModifier struct {
	ID                  uint64         `json:"id"`
	OrderItemID         int32          `json:"orderItemId"`
	ParentModifierID    sql.NullString `json:"parentModifierId"`
	SubParentModifierID sql.NullString `json:"subParentModifierId"`
	ModifierID          string         `json:"modifierId"`
	ModifierGroupName   string         `json:"modifierGroupName"`
	ModifierOptionID    string         `json:"modifierOptionId"`
	ModifierOptionName  string         `json:"modifierOptionName"`
	Amount              string         `json:"amount"`
	Quantity            string         `json:"quantity"`
	CreatedAt           sql.NullTime   `json:"createdAt"`
	UpdatedAt           sql.NullTime   `json:"updatedAt"`
}

type PosRefreshToken struct {
	UserID    uint64       `json:"userId"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expiresAt"`
	CreatedAt sql.NullTime `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
}

type Role struct {
	ID          uint32       `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"createdAt"`
	UpdatedAt   sql.NullTime `json:"updatedAt"`
}

type Shop struct {
	ID                           uint64         `json:"id"`
	Name                         string         `json:"name"`
	FranchiseID                  int32          `json:"franchiseId"`
	Code                         string         `json:"code"`
	Email                        sql.NullString `json:"email"`
	Address                      sql.NullString `json:"address"`
	Branch                       sql.NullString `json:"branch"`
	ContactNo                    sql.NullString `json:"contactNo"`
	BusinessRegNo                sql.NullString `json:"businessRegNo"`
	SocketCode                   sql.NullString `json:"socketCode"`
	Status                       string         `json:"status"`
	OrderStatus                  string         `json:"orderStatus"`
	LastUpdatedMenu              sql.NullInt32  `json:"lastUpdatedMenu"`
	LastPosSynced                sql.NullTime   `json:"lastPosSynced"`
	ServiceAvailability          sql.NullString `json:"serviceAvailability"`
	CreatedAt                    sql.NullTime   `json:"createdAt"`
	UpdatedAt                    sql.NullTime   `json:"updatedAt"`
	MinimumAmountForFreeDelivery sql.NullString `json:"minimumAmountForFreeDelivery"`
	MinimumAmountForDelivery     sql.NullString `json:"minimumAmountForDelivery"`
	OneTimePromotionValue        sql.NullString `json:"oneTimePromotionValue"`
	OneTimePromotionSpendAmount  sql.NullString `json:"oneTimePromotionSpendAmount"`
	Latitude                     sql.NullString `json:"latitude"`
	Longitude                    sql.NullString `json:"longitude"`
	GoogleLocationUrl            sql.NullString `json:"googleLocationUrl"`
	OneTimePromotionType         sql.NullString `json:"oneTimePromotionType"`
	MaximumPromotionValue        string         `json:"maximumPromotionValue"`
	SelectedMenu                 sql.NullInt32  `json:"selectedMenu"`
	IsDefault                    bool           `json:"isDefault"`
	CountryCode                  sql.NullString `json:"countryCode"`
	Timezone                     string         `json:"timezone"`
	Currency                     string         `json:"currency"`
	CurrencyCode                 string         `json:"currencyCode"`
	PrintReceiptAccept           bool           `json:"printReceiptAccept"`
	NumberOfReceipt              int32          `json:"numberOfReceipt"`
	DeliveryPlatformEnable       bool           `json:"deliveryPlatformEnable"`
	RunTestOrder                 bool           `json:"runTestOrder"`
	HasCashPayment               bool           `json:"hasCashPayment"`
	HasCardPayment               bool           `json:"hasCardPayment"`
	TblCommissionPerHead         string         `json:"tblCommissionPerHead"`
	TblRefCommissionPerHead      string         `json:"tblRefCommissionPerHead"`
	TransferDestination          sql.NullString `json:"transferDestination"`
	DelivergateAccount           bool           `json:"delivergateAccount"`
	PrinterStatus                bool           `json:"printerStatus"`
	DeletedAt                    sql.NullTime   `json:"deletedAt"`
	HasCollectionPoints          bool           `json:"hasCollectionPoints"`
	CollectionPointsNote         sql.NullString `json:"collectionPointsNote"`
	UserInteractionStatus        bool           `json:"userInteractionStatus"`
	InteractionTimeout           sql.NullInt32  `json:"interactionTimeout"`
}

type Tenant struct {
	ID                  uint64       `json:"id"`
	Host                string       `json:"host"`
	Port                string       `json:"port"`
	DatabaseName        string       `json:"databaseName"`
	XTenantCode         string       `json:"xTenantCode"`
	Username            string       `json:"username"`
	Password            string       `json:"password"`
	ServerClientID      int32        `json:"serverClientId"`
	ServerClientSecret  string       `json:"serverClientSecret"`
	SiteName            string       `json:"siteName"`
	PrdDomain           string       `json:"prdDomain"`
	CreatedAt           sql.NullTime `json:"createdAt"`
	UpdatedAt           sql.NullTime `json:"updatedAt"`
	HasWebshop          bool         `json:"hasWebshop"`
	EnableDusk          bool         `json:"enableDusk"`
	DuskPort            string       `json:"duskPort"`
	SyncStatus          bool         `json:"syncStatus"`
	SyncWebshopStatus   bool         `json:"syncWebshopStatus"`
	HasMultishop        bool         `json:"hasMultishop"`
	SendReports         bool         `json:"sendReports"`
	RetryAuthentication bool         `json:"retryAuthentication"`
}

type User struct {
	ID              uint64         `json:"id"`
	Name            string         `json:"name"`
	LastName        sql.NullString `json:"lastName"`
	Email           string         `json:"email"`
	Address         sql.NullString `json:"address"`
	ContactNo       sql.NullString `json:"contactNo"`
	EmailVerifiedAt sql.NullTime   `json:"emailVerifiedAt"`
	Password        string         `json:"password"`
	Pin             sql.NullString `json:"pin"`
	Status          sql.NullString `json:"status"`
	RememberToken   sql.NullString `json:"rememberToken"`
	ExpoToken       sql.NullString `json:"expoToken"`
	DeviceID        sql.NullString `json:"deviceId"`
	CreatedAt       sql.NullTime   `json:"createdAt"`
	UpdatedAt       sql.NullTime   `json:"updatedAt"`
}

type UserRole struct {
	ID        uint32       `json:"id"`
	UserID    uint32       `json:"userId"`
	RoleID    uint32       `json:"roleId"`
	CreatedAt sql.NullTime `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
}

type WebshopMenu struct {
	ID                 uint64         `json:"id"`
	MainMenuID         int32          `json:"mainMenuId"`
	SubmenuID          sql.NullInt32  `json:"submenuId"`
	PlatformID         sql.NullInt32  `json:"platformId"`
	DeliveryPlatformID int32          `json:"deliveryPlatformId"`
	Status             sql.NullInt32  `json:"status"`
	OutletID           int32          `json:"outletId"`
	Day                sql.NullString `json:"day"`
	From               sql.NullString `json:"from"`
	To                 sql.NullString `json:"to"`
	Menu               sql.NullString `json:"menu"`
	CategoryIds        sql.NullString `json:"categoryIds"`
	CreatedAt          sql.NullTime   `json:"createdAt"`
	UpdatedAt          sql.NullTime   `json:"updatedAt"`
}
