// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_item_modifier_query.sql

package db

import (
	"context"
	"database/sql"
)

const createOrderItemModifier = `-- name: CreateOrderItemModifier :exec
INSERT INTO
    order_item_modifier (
        order_item_id,
        parent_modifier_id,
        sub_parent_modifier_id,
        modifier_id,
        modifier_group_name,
        modifier_option_id,
        modifier_option_name,
        amount,
        quantity,
        created_at,
        updated_at
    )
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    )
`

type CreateOrderItemModifierParams struct {
	OrderItemID         int32          `json:"orderItemId"`
	ParentModifierID    sql.NullString `json:"parentModifierId"`
	SubParentModifierID sql.NullString `json:"subParentModifierId"`
	ModifierID          string         `json:"modifierId"`
	ModifierGroupName   string         `json:"modifierGroupName"`
	ModifierOptionID    string         `json:"modifierOptionId"`
	ModifierOptionName  string         `json:"modifierOptionName"`
	Amount              string         `json:"amount"`
	Quantity            string         `json:"quantity"`
	CreatedAt           sql.NullTime   `json:"createdAt"`
	UpdatedAt           sql.NullTime   `json:"updatedAt"`
}

func (q *Queries) CreateOrderItemModifier(ctx context.Context, arg *CreateOrderItemModifierParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItemModifier,
		arg.OrderItemID,
		arg.ParentModifierID,
		arg.SubParentModifierID,
		arg.ModifierID,
		arg.ModifierGroupName,
		arg.ModifierOptionID,
		arg.ModifierOptionName,
		arg.Amount,
		arg.Quantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
